name: NoDatingPE
main: Vaivez66\NoDatingPE\NoDating
version: 1.0.1
api: [1.12.0, 2.0.0]
load: POSTWORLD
authors: [Vaivez66]
description: "Stop those daters!"
commands:
  nd:
    description: "Main command"
    usage: "/nd <add|remove|list> [word]"
permissions:
  no.dating.pe:
    description: "Permission to perform command"
    default: op
  no.dating.pe.bypass:
    description: "Permission to bypass from blocking"
    default: false
