
# Available types:
#   - broadcast
#   - block
#   - kick
type: block
# The message that will send
# You can use {player} to mention their name
message: '{RED}Do not use this server as a dating service!'
# Blocked dating words
domain:
  - "dating"
  - "bf"
  - "gf"
# If true, it will detect a sign
detect.sign: true
# Lines that will change if player advertise on sign
lines:
  - '============='
  - 'No Dating!'
  - '============='
  - ''
# The command that will protected from advertising
blocked.cmd:
  - "/me"
  - "/tell"
